var annotated_dup =
[
    [ "Building", "classBuilding.html", "classBuilding" ],
    [ "Family", "classFamily.html", "classFamily" ],
    [ "FamilyTask", "classFamilyTask.html", "classFamilyTask" ],
    [ "GraphHandler", "classGraphHandler.html", "classGraphHandler" ],
    [ "GraphWindow", "classGraphWindow.html", "classGraphWindow" ],
    [ "House", "classHouse.html", "classHouse" ],
    [ "MainMenu", "classMainMenu.html", "classMainMenu" ],
    [ "Market", "classMarket.html", "classMarket" ],
    [ "MenuSlider", "classMenuSlider.html", "classMenuSlider" ],
    [ "MoveCamera", "classMoveCamera.html", "classMoveCamera" ],
    [ "PathMaker", "classPathMaker.html", "classPathMaker" ],
    [ "Person", "classPerson.html", "classPerson" ],
    [ "School", "classSchool.html", "classSchool" ],
    [ "Settings", "classSettings.html", "classSettings" ],
    [ "SettingsMenu", "classSettingsMenu.html", "classSettingsMenu" ],
    [ "StatusHandler", "classStatusHandler.html", "classStatusHandler" ],
    [ "VirusType", "classVirusType.html", "classVirusType" ],
    [ "WorkPlace", "classWorkPlace.html", "classWorkPlace" ],
    [ "WorkTime", "structWorkTime.html", "structWorkTime" ],
    [ "World", "classWorld.html", "classWorld" ],
    [ "WorldCell", "classWorldCell.html", "classWorldCell" ],
    [ "WorldGenerator", "classWorldGenerator.html", "classWorldGenerator" ]
];