Bomberman: FamilyTask Class Reference
FamilyTask Class Reference
Handles the family's update on a separate core
Public Member Functions
FamilyTask (List< Family > families)
Creates a new object
void Start ()
Starts the family task
Private Member Functions
async Task FamilyTasks ()
The family task repeats endlessly
Private Attributes
List< Family > families
Detailed Description
Handles the family's update on a separate core
Definition at line 8 of file FamilyTask.cs.
Constructor & Destructor Documentation
FamilyTask()
FamilyTask.FamilyTask (List< Family > families) inline
Creates a new object
Parameters
families Reference to the family list in the world
Definition at line 18 of file FamilyTask.cs.
     {
         this.families = families;
     }
References families.
Member Function Documentation
Start()
void FamilyTask.Start () inline
Starts the family task
Definition at line 27 of file FamilyTask.cs.
     {
         Task.Run(() => FamilyTasks());
     }
References FamilyTasks().
Referenced by World.Awake().
FamilyTasks()
async Task FamilyTask.FamilyTasks () inline private
The family task repeats endlessly
Definition at line 36 of file FamilyTask.cs.
     {
         Stopwatch stopwatch = new Stopwatch();
         stopwatch.Start();
         while (Settings.TaskRun)
         {
             for (int i = 0; i < families.Count; i++)
             {
                 families[i].UpdateFamilySupplies((float)stopwatch.ElapsedMilliseconds / 1000f);
             }
             UnityEngine.Debug.Log("FamilyTask is running");
             stopwatch.Restart();
             await Task.Delay(1000);
         }
     }
References families, and Settings.TaskRun.
Referenced by Start().
Member Data Documentation
families
List<Family> FamilyTask.families private
Definition at line 11 of file FamilyTask.cs.
Referenced by FamilyTask(), and FamilyTasks().
The documentation for this class was generated from the following file:
Assets/Scripts/Tasks/FamilyTask.cs