Bomberman: GraphWindow Class Reference
GraphWindow Class Reference
Public Member Functions
void InitGraph (int maxValue)
void AddValue (float value)
Adds a value to the graph
Private Member Functions
void CreateLabels ()
void CreateSeparators ()
void CreatePoint (Vector2 anchoredPos)
void PushToTheLeft ()
void CreateDotConnection (Vector2 startPosition, Vector2 endPosition)
void DisplayMultiplePoints (List< float > values)
Private Attributes
Sprite circleSprite
RectTransform graphRect
int highest = 50
int maxNumberOfPoints = 10
int ySeparatorCount = 10
float distanceBetweenPoints = 0
List< Text > xLabels = new List<Text>()
Color graphElementColor = Color.white
List< RectTransform > points
List< RectTransform > lines
Detailed Description
Definition at line 6 of file GraphWindow.cs.
Member Function Documentation
InitGraph()
void GraphWindow.InitGraph (int maxValue) inline
Definition at line 21 of file GraphWindow.cs.
     {
         this.highest = maxValue;
         points = new List<RectTransform>();
         lines = new List<RectTransform>();
         graphRect = this.GetComponent<RectTransform>();
         //CreateCircle(new Vector2(2, 2));
         distanceBetweenPoints = graphRect.rect.width / maxNumberOfPoints;
         CreateSeparators();
         CreateLabels();
     }
References CreateLabels(), CreateSeparators(), distanceBetweenPoints, graphRect, lines, maxNumberOfPoints, and points.
Referenced by StatusHandler.InitStatus().
CreateLabels()
void GraphWindow.CreateLabels () inline private
Definition at line 35 of file GraphWindow.cs.
     {
         Text label = new GameObject($"label", typeof(Text)).GetComponent<Text>();
         label.transform.SetParent(graphRect);
         RectTransform rectTransform = label.GetComponent<RectTransform>();
         rectTransform.anchorMin = new Vector2(0, 0);
         rectTransform.anchorMax = new Vector2(0, 0);
         rectTransform.localScale = new Vector3(1, 1, 1);
         rectTransform.anchoredPosition = new Vector3(graphRect.rect.width / 2, -20, 1);
         label.text = "day";
         label.color = graphElementColor;
         label.alignment = TextAnchor.MiddleCenter;
         label.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
         //X axis
         for (int i = 1; i <= maxNumberOfPoints; i++)
         {
             Text labelX = Instantiate(label, graphRect, false);
             labelX.GetComponent<RectTransform>().anchoredPosition = new Vector3(distanceBetweenPoints * i, -7.5f, 1);
             labelX.text = (i).ToString();
             xLabels.Add(labelX);
         }
         int yValueDifference = highest / ySeparatorCount;
         float yValueDist = graphRect.rect.height / ySeparatorCount;
         //Y axis
         for (int i = 0; i <= ySeparatorCount; i++)
         {
             Text labelY = Instantiate<Text>(label, graphRect, false);
             labelY.GetComponent<RectTransform>().anchoredPosition = new Vector3(-60, i * yValueDist, 1);
             labelY.text = (i * yValueDifference).ToString();
             labelY.alignment = TextAnchor.MiddleRight;
         }
     }
References distanceBetweenPoints, graphElementColor, graphRect, highest, maxNumberOfPoints, xLabels, and ySeparatorCount.
Referenced by InitGraph().
CreateSeparators()
void GraphWindow.CreateSeparators () inline private
Definition at line 72 of file GraphWindow.cs.
     {
         //X separators
         float yValueDist = graphRect.rect.height / ySeparatorCount;
         RectTransform xSeparator = new GameObject("xLine", typeof(Image)).GetComponent<RectTransform>();
         xSeparator.transform.SetParent(graphRect);
         xSeparator.anchorMin = new Vector2(0, 0);
         xSeparator.anchorMax = new Vector2(0, 0);
         xSeparator.localScale = new Vector3(1, 1, 1);
         xSeparator.sizeDelta = new Vector2(graphRect.rect.width, 1);
         xSeparator.anchoredPosition = new Vector3(graphRect.rect.width / 2, 0, 1);
         xSeparator.GetComponent<Image>().color = new Color(1, 1, 1, 0.4f);
         for (int i = 1; i < maxNumberOfPoints; i++)
         {
             RectTransform newXline = Instantiate<RectTransform>(xSeparator, graphRect, false);
             newXline.anchoredPosition = new Vector3(graphRect.rect.width / 2, i * yValueDist, 1);
         }
         //Y separators
         RectTransform ySeparator = Instantiate<RectTransform>(xSeparator, graphRect, false);
         ySeparator.sizeDelta = new Vector2(1, graphRect.rect.height);
         ySeparator.anchoredPosition = new Vector3(0, graphRect.rect.height / 2, 1);
         for (int i = 1; i < ySeparatorCount; i++)
         {
             RectTransform newYline = Instantiate<RectTransform>(ySeparator, graphRect, false);
             newYline.anchoredPosition = new Vector3(i * distanceBetweenPoints, graphRect.rect.height / 2, 1);
         }
     }
References distanceBetweenPoints, graphRect, maxNumberOfPoints, and ySeparatorCount.
Referenced by InitGraph().
CreatePoint()
void GraphWindow.CreatePoint (Vector2 anchoredPos) inline private
Definition at line 103 of file GraphWindow.cs.
     {
         if (points.Count != 0)
         {
             CreateDotConnection(points[points.Count - 1].GetComponent<RectTransform>().anchoredPosition, anchoredPos);
         }
         if (points.Count == maxNumberOfPoints)
         {
             RectTransform rectTransform = points[0];
             points.RemoveAt(0);
             rectTransform.anchoredPosition = anchoredPos;
             Destroy(lines[0].gameObject);
             lines.RemoveAt(0);
             points.Add(rectTransform);
             PushToTheLeft();
         }
         else
         {
             GameObject circle = new GameObject("circle", typeof(Image));
             circle.transform.SetParent(graphRect, false);
             circle.GetComponent<Image>().sprite = circleSprite;
             circle.GetComponent<Image>().color = Color.yellow;
             RectTransform rectTransform = circle.GetComponent<RectTransform>();
             rectTransform.anchoredPosition = anchoredPos;
             rectTransform.sizeDelta = new Vector2(10, 10);
             rectTransform.anchorMin = new Vector2(0, 0);
             rectTransform.anchorMax = new Vector2(0, 0);
             points.Add(rectTransform);
         }
     }
References circleSprite, CreateDotConnection(), graphRect, lines, maxNumberOfPoints, points, and PushToTheLeft().
Referenced by AddValue().
PushToTheLeft()
void GraphWindow.PushToTheLeft () inline private
Definition at line 136 of file GraphWindow.cs.
     {
         foreach (var point in points)
         {
             point.anchoredPosition = new Vector3(point.anchoredPosition.x - distanceBetweenPoints, point.anchoredPosition.y);
         }
         foreach (var line in lines)
         {
             line.anchoredPosition = new Vector3(line.anchoredPosition.x - distanceBetweenPoints, line.anchoredPosition.y);
         }
         int smallest = System.Convert.ToInt32(xLabels[0].text) + 1;
         for (int i = 0; i < maxNumberOfPoints; i++)
         {
             xLabels[i].text = (smallest + i).ToString();
         }
     }
References distanceBetweenPoints, lines, maxNumberOfPoints, points, and xLabels.
Referenced by CreatePoint().
AddValue()
void GraphWindow.AddValue (float value) inline
Adds a value to the graph
Parameters
value What we want to illustrate
Definition at line 160 of file GraphWindow.cs.
     {
         if (points == null)
         {
             return;
         }
         CreatePoint(new Vector2(distanceBetweenPoints * points.Count, value / highest * graphRect.rect.height));
     }
References CreatePoint(), distanceBetweenPoints, graphRect, highest, and points.
Referenced by DisplayMultiplePoints(), StatusHandler.InitStatus(), and StatusHandler.UpdateDayTime().
CreateDotConnection()
void GraphWindow.CreateDotConnection (Vector2 startPosition, Vector2 endPosition) inline private
Definition at line 172 of file GraphWindow.cs.
     {
         GameObject line = new GameObject("line", typeof(Image));
         line.transform.SetParent(graphRect);
         line.GetComponent<Image>().color = graphElementColor;
         RectTransform rectTransform = line.GetComponent<RectTransform>();
         Vector2 dir = (endPosition - startPosition).normalized;
         float dist = Vector2.Distance(startPosition, endPosition);
         rectTransform.sizeDelta = new Vector2(dist, 2.5f);
         rectTransform.anchorMin = new Vector2(0, 0);
         rectTransform.anchorMax = new Vector2(0, 0);
         rectTransform.localScale = new Vector3(1f, 1f, 1f);
         rectTransform.anchoredPosition = startPosition + dir * dist * 0.5f;
         rectTransform.localEulerAngles = new Vector3(0, 0, Mathf.Atan2(dir.y, dir.x) * 180 / Mathf.PI);
         lines.Add(rectTransform);
     }
References graphElementColor, graphRect, and lines.
Referenced by CreatePoint().
DisplayMultiplePoints()
void GraphWindow.DisplayMultiplePoints (List< float > values) inline private
Definition at line 191 of file GraphWindow.cs.
     {
         for (int i = 0; i < values.Count; i++)
         {
             AddValue(values[i]);
         }
     }
References AddValue().
Member Data Documentation
circleSprite
Sprite GraphWindow.circleSprite private
Definition at line 9 of file GraphWindow.cs.
Referenced by CreatePoint().
graphRect
RectTransform GraphWindow.graphRect private
Definition at line 11 of file GraphWindow.cs.
Referenced by AddValue(), CreateDotConnection(), CreateLabels(), CreatePoint(), CreateSeparators(), and InitGraph().
highest
int GraphWindow.highest = 50 private
Definition at line 12 of file GraphWindow.cs.
Referenced by AddValue(), and CreateLabels().
maxNumberOfPoints
int GraphWindow.maxNumberOfPoints = 10 private
Definition at line 13 of file GraphWindow.cs.
Referenced by CreateLabels(), CreatePoint(), CreateSeparators(), InitGraph(), and PushToTheLeft().
ySeparatorCount
int GraphWindow.ySeparatorCount = 10 private
Definition at line 14 of file GraphWindow.cs.
Referenced by CreateLabels(), and CreateSeparators().
distanceBetweenPoints
float GraphWindow.distanceBetweenPoints = 0 private
Definition at line 15 of file GraphWindow.cs.
Referenced by AddValue(), CreateLabels(), CreateSeparators(), InitGraph(), and PushToTheLeft().
xLabels
List<Text> GraphWindow.xLabels = new List<Text>() private
Definition at line 16 of file GraphWindow.cs.
Referenced by CreateLabels(), and PushToTheLeft().
graphElementColor
Color GraphWindow.graphElementColor = Color.white private
Definition at line 17 of file GraphWindow.cs.
Referenced by CreateDotConnection(), and CreateLabels().
points
List<RectTransform> GraphWindow.points private
Definition at line 18 of file GraphWindow.cs.
Referenced by AddValue(), CreatePoint(), InitGraph(), and PushToTheLeft().
lines
List<RectTransform> GraphWindow.lines private
Definition at line 19 of file GraphWindow.cs.
Referenced by CreateDotConnection(), CreatePoint(), InitGraph(), and PushToTheLeft().
The documentation for this class was generated from the following file:
Assets/Scripts/Graph/GraphWindow.cs