Bomberman: World Class Reference
World Class Reference
The world
Public Member Functions
Building LookForBuilding (int xCoord, int yCoord, int maxSearchRange, BuildingType buildingType)
Looks for the nearest building with the specified type
Building GetOccupationBuilding (int xCoord, int yCoord, BuildingType buildingType)
Search for a buildig for the person to work at So it isn't only the nearest building and virus can spread more realistically
void InfectInRange (Vector2 worldCellIndex, Vector2 personPos, VirusType virus)
Infect everyone on the same cell
void AddPersonToWorldCell (Vector2 indices, Person personToAdd)
Adds a person to the world cell
void MovePerson (Vector2 oldPos, Vector2 newPos, Person personToMove)
Moves a person from the old position to the new position int the world cells
bool CreatePath (out List< Vector2 > path, Vector2 startCoord, Vector2 goalCoord)
Creates a path from the start vector to the goal vector
void Infected (AgeGroup ageGrp)
Updates the infected status (increase it by one)
void Recovered (AgeGroup ageGrp)
Updates the infected status (decrease it by one)
void Died (Person person)
Updates the appropiate statuses when someone died
void IncreasePeople (AgeGroup ageGrp)
Increase the number of people in the status
Static Public Member Functions
static float CalcDistance (Vector2 coord1, Vector2 coord2)
Calculates the distance between two vectors
Public Attributes
GameObject DefaultPerson
WorldGenerator WorldGenerator
StatusHandler StatusHandler
float dayTime = 0f
The time of the day 1 = 1sec
Properties
ushort DayCounter = 0 [get, private set]
The number of days passed
int XSize [get]
The X size of the map
int YSize [get]
The Y size of the map
int cellXCount [get]
The number of cells in the worldcells array on the x axis
int cellYCount [get]
The number of cells in the worldcells array on the y axis
WorldCell[,] worldCells [get]
The cells of the world this can be used to find nearby objects
byte CellSize [get]
A size of a single world cell
CellType[,] Cells [get]
The type of each of cell
int PeopleCount [get]
Private Member Functions
void Awake ()
void Update ()
async void HandleDailyTasks ()
Handles all of the daily tasks
void Vaccinate ()
Handles the daily vaccination Task
void WriteOutDailyData (StreamWriter streamWriter)
Writes out the current statuses into a file
void ReadInViruses (string nameOfTheFile="viruses.json")
void InfectRandomFamilies (VirusType virus)
void FillWorldWithFamilies (int familyCount)
void OnApplicationQuit ()
Handle zombies
Private Attributes
PathMaker pathMaker
List< VirusType > viruses
List< Family > families
List< Person > people
bool newDay = false
System.Random rnd = new System.Random()
FamilyTask familyTask
Detailed Description
The world
Definition at line 13 of file World.cs.
Member Function Documentation
Awake()
void World.Awake () inline private
Definition at line 81 of file World.cs.
     {
         WorldGenerator.GenerateWorld();
         pathMaker = new PathMaker((short)WorldGenerator.Size, this);
         FillWorldWithFamilies(WorldGenerator.Buildings[BuildingType.House].Count);
         ReadInViruses();
         Settings.TaskRun = true;
         Task.Run(() => HandleDailyTasks());
         //Starts the tasks for the families
         familyTask = new FamilyTask(families);
         familyTask.Start();
         StatusHandler.InitStatus();
         Debug.Log(people.Count);
     }
References WorldGenerator.Buildings, families, familyTask, FillWorldWithFamilies(), WorldGenerator.GenerateWorld(), HandleDailyTasks(), StatusHandler.InitStatus(), pathMaker, people, ReadInViruses(), WorldGenerator.Size, FamilyTask.Start(), and Settings.TaskRun.
Update()
void World.Update () inline private
Definition at line 98 of file World.cs.
     {
         dayTime += Time.deltaTime * Settings.RealTimeToSimulationTime;
         if (dayTime >= 86400f)
         {
             DayCounter++;
             StatusHandler.UpdateDayTime(DayCounter);
             dayTime = 0f;
             newDay = true;
         }
     }
References DayCounter, dayTime, newDay, Settings.RealTimeToSimulationTime, and StatusHandler.UpdateDayTime().
HandleDailyTasks()
async void World.HandleDailyTasks () inline private
Handles all of the daily tasks
Definition at line 114 of file World.cs.
     {
         Debug.Log("Started task");
         StreamWriter streamWriter = new StreamWriter("dailyData.csv");
         streamWriter.AutoFlush = true;
         await streamWriter.WriteLineAsync("Day;Current people count;Underage people count;" +
             "Adult people count;Infected count;Underage infected count; Adult infected count" +
             "Lockdown status");
         while (Settings.TaskRun)
         {
             if (newDay)
             {
                 newDay = false;
                 Vaccinate();
                 WriteOutDailyData(streamWriter);
             }
             await Task.Delay(100);
         }
     }
References newDay, Settings.TaskRun, Vaccinate(), and WriteOutDailyData().
Referenced by Awake().
Vaccinate()
void World.Vaccinate () inline private
Handles the daily vaccination Task
Definition at line 139 of file World.cs.
     {
         List<Person> unvaccinated = new List<Person>();
         for (int i = 0; i < people.Count; i++)
         {
             if (people[i].Infectable() && !people[i].AntiVacination)
             {
                 unvaccinated.Add(people[i]);
             }
         }
         for (int i = 0; i < Settings.DailyVaccineAmount; i++)
         {
             if (unvaccinated.Count == 0)
             {
                 break;
             }
             int personIndex = rnd.Next(0, unvaccinated.Count);
             unvaccinated[personIndex].GetVaccinated();
             unvaccinated.RemoveAt(personIndex);
         }
     }
References Settings.DailyVaccineAmount, people, and rnd.
Referenced by HandleDailyTasks().
WriteOutDailyData()
void World.WriteOutDailyData (StreamWriter streamWriter) inline private
Writes out the current statuses into a file
Definition at line 168 of file World.cs.
     {
         streamWriter.WriteLine(StatusHandler.ToString());
     }
References StatusHandler.ToString().
Referenced by HandleDailyTasks().
ReadInViruses()
void World.ReadInViruses (string nameOfTheFile = "viruses.json") inline private
Definition at line 175 of file World.cs.
     {
         viruses = JsonConvert.DeserializeObject<List<VirusType>>(System.IO.File.ReadAllText(nameOfTheFile));
         foreach (var virus in viruses)
         {
             InfectRandomFamilies(virus);
         }
     }
References InfectRandomFamilies(), and viruses.
Referenced by Awake().
InfectRandomFamilies()
void World.InfectRandomFamilies (VirusType virus) inline private
Definition at line 187 of file World.cs.
     {
         for (int i = 0; i < Settings.NumberOfFamiliesToInfectOnStart; i++)
         {
             families[Random.Range(0, families.Count)].GetInitialInfection(virus);
         }
     }
References families, and Settings.NumberOfFamiliesToInfectOnStart.
Referenced by ReadInViruses().
FillWorldWithFamilies()
void World.FillWorldWithFamilies (int familyCount) inline private
Definition at line 197 of file World.cs.
     {
         people = new List<Person>();
         GameObject familiesParent = new GameObject("families");
         familiesParent.transform.parent = this.transform;
         int houseIndex = Random.Range(0, WorldGenerator.Buildings[BuildingType.House].Count);
         families = new List<Family>();
         for (int i = 0; i < familyCount; i++)
         {
             if (WorldGenerator.Buildings[BuildingType.House].Count <= i)
             {
                 break;
             }
             GameObject family = new GameObject("family" + i, typeof(Family));
             family.transform.parent = familiesParent.transform;
             family.GetComponent<Family>().SetDefaultParams((House)WorldGenerator.Buildings[BuildingType.House][i], (byte)Random.Range(Settings.MinSizeOfFamily, Settings.MaxSizeOfFamily + 1), this);
             families.Add(family.GetComponent<Family>());
             ((House)(WorldGenerator.Buildings[BuildingType.House][i])).Occupy();
             people.AddRange(families.Last().peopleInFamily);
             //  WorldGenerator.Houses.RemoveAt(houseIndex);
         }
     }
References WorldGenerator.Buildings, families, House, Settings.MaxSizeOfFamily, Settings.MinSizeOfFamily, and people.
Referenced by Awake().
LookForBuilding()
Building World.LookForBuilding (int xCoord, int yCoord, int maxSearchRange, BuildingType buildingType) inline
Looks for the nearest building with the specified type
Parameters
xCoord Start of the search on the x axis
yCoord Start of the search on the y axis
maxSearchRange The maximum search range
buildingType The type of the building
Returns
The building it found returns with null if it didn't found any
Definition at line 229 of file World.cs.
     {
         Direction dir = Direction.Left; //Direction the iteration is going
         byte length = 0; //The length of the iteration
         int row = yCoord / CellSize; //The row in the matrix
         int col = xCoord / CellSize; //The col in the matrix
         do
         {
             //Increment the length by one every 2 cycle
             if ((byte)dir % 2 == 0)
             {
                 length++;
             }
             //Iterate through the side of the spiral
             for (int i = 0; i < length; i++)
             {
                 if ((byte)dir % 2 == 0)
                 {
                     col += (byte)dir - 1;
                 }
                 else
                 {
                     row -= (byte)dir - 2;
                 }
                 if (row >= cellYCount || row < 0 || col >= cellXCount || col < 0)
                 {
                     continue;
                 }
                 Building possibleBuilding = worldCells[row, col].GetAvalibleBuilding(buildingType);
                 if (possibleBuilding != null)
                 {
                     return possibleBuilding;
                 }
             }
             //Change the direction
             if (dir == Direction.Up)
             {
                 dir = Direction.Left;
             }
             else
             {
                 dir += 1;
             }
         } while (((float)length / 2f) <= maxSearchRange);
         return null;
     }
References CellSize, cellXCount, cellYCount, WorldCell.GetAvalibleBuilding(), and worldCells.
Referenced by Family.SetDefaultParams().
GetOccupationBuilding()
Building World.GetOccupationBuilding (int xCoord, int yCoord, BuildingType buildingType) inline
Search for a buildig for the person to work at So it isn't only the nearest building and virus can spread more realistically
Parameters
xCoord Start of the search on the x axis
yCoord Start of the search on the y axis
maxSearchRange The maximum search range
buildingType The type of the building
Returns
The building it found returns with null if it didn't found any
Definition at line 288 of file World.cs.
     {
         List<Building> tempBuildings = WorldGenerator.Buildings[buildingType].Select(x => x).ToList();
         do
         {
             int randomIndex = Random.Range(0, tempBuildings.Count);
             if (tempBuildings[randomIndex].HasFreeSpace())
             {
                 return tempBuildings[randomIndex];
             }
             tempBuildings.RemoveAt(randomIndex);
         } while (tempBuildings.Count != 0);
         return null;
     }
References WorldGenerator.Buildings.
Referenced by Person.FindSchool(), and Person.FindWorkPlace().
InfectInRange()
void World.InfectInRange (Vector2 worldCellIndex, Vector2 personPos, VirusType virus) inline
Infect everyone on the same cell
Parameters
worldCellIndex The index of the world cell
personPos The source of the infection
virus The virus
Definition at line 313 of file World.cs.
     {
         /*  for (int i = (int)worldCellIndex.y - 1; i <= worldCellIndex.y + 1; i++)
           {
               if (i < 0 || i >= cellYCount)
               {
                   continue;
               }
               for (int j = (int)worldCellIndex.x - 1; j < worldCellIndex.x + 1; j++)
               {
                   if (j < 0 || i >= cellXCount)
                   {
                       continue;
                   }
                   this.worldCells[i, j].TryToInfectEveryOneInRange(personPos, range);
               }
           }*/
         this.worldCells[(int)worldCellIndex.y, (int)worldCellIndex.x].TryToInfectEveryOneInRange(personPos, virus);
     }
References WorldCell.TryToInfectEveryOneInRange(), and worldCells.
Referenced by Person.InfectOutside().
AddPersonToWorldCell()
void World.AddPersonToWorldCell (Vector2 indices, Person personToAdd) inline
Adds a person to the world cell
Parameters
xIndex The x index of the world cell
yIndex The y index of the world cell
personToAdd The person to add
Definition at line 341 of file World.cs.
     {
         this.worldCells[(int)indices.y, (int)indices.x].AddPerson(personToAdd);
     }
References WorldCell.AddPerson(), and worldCells.
Referenced by Person.SetDefaultParameters().
MovePerson()
void World.MovePerson (Vector2 oldPos, Vector2 newPos, Person personToMove) inline
Moves a person from the old position to the new position int the world cells
Parameters
personToMove Reference to the person to move
oldPos The old worldCell position
newPos The new worldCell position
Definition at line 353 of file World.cs.
     {
         if (personToMove == null)
         {
             return;
         }
         this.worldCells[(int)oldPos.y, (int)oldPos.x].RemovePerson(personToMove);
         this.worldCells[(int)newPos.y, (int)newPos.x].AddPerson(personToMove);
     }
References WorldCell.AddPerson(), WorldCell.RemovePerson(), and worldCells.
Referenced by Person.MoveInWorldCellGrid().
CreatePath()
bool World.CreatePath (out List< Vector2 > path, Vector2 startCoord, Vector2 goalCoord) inline
Creates a path from the start vector to the goal vector
Parameters
path The path it will create
startCoord The start of the path (must be on the road)
goalCoord The goal of the path (must be on the road)
Returns
true if it created a path false if it failed to create
Definition at line 373 of file World.cs.
     {
         Debug.Log("Generated path");
         return pathMaker.CreatePath(out path, startCoord, goalCoord);
     }
References PathMaker.CreatePath(), and pathMaker.
Referenced by Person.CreatePaths(), and Family.SetDefaultParams().
CalcDistance()
static float World.CalcDistance (Vector2 coord1, Vector2 coord2) inline static
Calculates the distance between two vectors
Parameters
coord1 The first vector
coord2 The second vector
Returns
The distance
Definition at line 386 of file World.cs.
     {
         return Mathf.Sqrt(Mathf.Pow((coord1.x - coord2.x), 2) + Mathf.Pow((coord1.y - coord2.y), 2));
     }
Referenced by PathMaker.SearchForGoal().
Infected()
void World.Infected (AgeGroup ageGrp) inline
Updates the infected status (increase it by one)
Parameters
ageGrp Which age group is the infected from
Definition at line 396 of file World.cs.
     {
         StatusHandler.IncreaseInfectedCount(ageGrp);
     }
References StatusHandler.IncreaseInfectedCount().
Referenced by Person.InfectedInRange(), and Person.StartingInfected().
Recovered()
void World.Recovered (AgeGroup ageGrp) inline
Updates the infected status (decrease it by one)
Parameters
ageGrp Which age group is the infected from
Definition at line 406 of file World.cs.
     {
         StatusHandler.DecreaseInfectedCount(ageGrp);
     }
References StatusHandler.DecreaseInfectedCount().
Referenced by Person.Recovered().
Died()
void World.Died (Person person) inline
Updates the appropiate statuses when someone died
Parameters
person Reference to who died
Definition at line 416 of file World.cs.
     {
         if (person.IsInfected)
         {
             StatusHandler.DecreaseInfectedCount(person.AgeGroup);
         }
         this.people.Remove(person);
         StatusHandler.DecreasePeople(person.AgeGroup);
     }
References Person.AgeGroup, StatusHandler.DecreaseInfectedCount(), StatusHandler.DecreasePeople(), and Person.IsInfected.
Referenced by Person.Die().
IncreasePeople()
void World.IncreasePeople (AgeGroup ageGrp) inline
Increase the number of people in the status
Parameters
ageGrp Which age group is the person from
Definition at line 432 of file World.cs.
     {
         StatusHandler.IncreasePeople(ageGrp);
     }
References StatusHandler.IncreasePeople().
Referenced by Person.SetDefaultParameters().
OnApplicationQuit()
void World.OnApplicationQuit () inline private
Handle zombies
Definition at line 441 of file World.cs.
     {
         Settings.TaskRun = false;
     }
References Settings.TaskRun.
Member Data Documentation
DefaultPerson
GameObject World.DefaultPerson
Definition at line 16 of file World.cs.
Referenced by Family.SetDefaultParams().
WorldGenerator
WorldGenerator World.WorldGenerator
Definition at line 19 of file World.cs.
StatusHandler
StatusHandler World.StatusHandler
Definition at line 22 of file World.cs.
dayTime
float World.dayTime = 0f
The time of the day 1 = 1sec
Definition at line 27 of file World.cs.
Referenced by Person.DecideNextActionState(), Person.SetDefaultParameters(), and Update().
pathMaker
PathMaker World.pathMaker private
Definition at line 71 of file World.cs.
Referenced by Awake(), and CreatePath().
viruses
List<VirusType> World.viruses private
Definition at line 72 of file World.cs.
Referenced by ReadInViruses().
families
List<Family> World.families private
Definition at line 73 of file World.cs.
Referenced by Awake(), FillWorldWithFamilies(), and InfectRandomFamilies().
people
List<Person> World.people private
Definition at line 74 of file World.cs.
Referenced by Awake(), FillWorldWithFamilies(), and Vaccinate().
newDay
bool World.newDay = false private
Definition at line 75 of file World.cs.
Referenced by HandleDailyTasks(), and Update().
rnd
System.Random World.rnd = new System.Random() private
Definition at line 76 of file World.cs.
Referenced by Vaccinate().
familyTask
FamilyTask World.familyTask private
Definition at line 77 of file World.cs.
Referenced by Awake().
Property Documentation
DayCounter
ushort World.DayCounter = 0 get private set
The number of days passed
Definition at line 32 of file World.cs.
 { get; private set; } = 0;
Referenced by Update().
XSize
int World.XSize get
The X size of the map
Definition at line 37 of file World.cs.
 { get => WorldGenerator.Size; }
Referenced by PathMaker.PathMaker().
YSize
int World.YSize get
The Y size of the map
Definition at line 42 of file World.cs.
 { get => WorldGenerator.Size; }
Referenced by PathMaker.PathMaker().
cellXCount
int World.cellXCount get
The number of cells in the worldcells array on the x axis
Definition at line 47 of file World.cs.
 { get => WorldGenerator.cellXCount; }
Referenced by LookForBuilding().
cellYCount
int World.cellYCount get
The number of cells in the worldcells array on the y axis
Definition at line 52 of file World.cs.
 { get => WorldGenerator.cellYCount; }
Referenced by LookForBuilding().
worldCells
WorldCell [,] World.worldCells get
The cells of the world this can be used to find nearby objects
Definition at line 57 of file World.cs.
 { get => WorldGenerator.worldCells; }
Referenced by AddPersonToWorldCell(), InfectInRange(), LookForBuilding(), and MovePerson().
CellSize
byte World.CellSize get
A size of a single world cell
Definition at line 62 of file World.cs.
 { get => WorldGenerator.CellSize; }
Referenced by LookForBuilding(), Person.MoveInWorldCellGrid(), and Person.SetDefaultParameters().
Cells
CellType [,] World.Cells get
The type of each of cell
Definition at line 67 of file World.cs.
 { get => WorldGenerator.cells; }
Referenced by PathMaker.PathMaker().
PeopleCount
int World.PeopleCount get
Definition at line 69 of file World.cs.
 { get => people.Count; }
The documentation for this class was generated from the following file:
Assets/Scripts/Map/World.cs