Bomberman: Person Class Reference
Person Class Reference
A single worthless person
Public Member Functions
void SetDefaultParameters (World world, Family family, byte age)
Sets the person's initial states
bool Infectable ()
Checks if the person can be infected
void InfectedInRange (VirusType virus)
This should be called when someone tries to infect him
void StartingInfected (VirusType virus)
He is one of the many who rolled badly :(
void GetPath (ActionState nextActionState)
bool SendToTheShop ()
Tries to send this person to the shop
void GetVaccinated ()
The person gets vaccinated
Public Attributes
SpriteRenderer AgeCircle
SpriteRenderer StatusCircle
Vector2 nextMoveTarget
Properties
byte Age [get, private set]
The age of the person This will determine his occupation mostly
AgeGroup AgeGroup [get, private set]
What age group does he belongs to
Gender Gender [get, private set]
The gender of the person
float XPos [get]
The person's position on the x axis
float YPos [get]
The person's position on the y axis
bool IsInfected = false [get, private set]
Is the person infected
bool InQuarantine = false [get, private set]
Is the person in quarantine
bool IsInside [get]
Is the person inside a building
bool AntiVacination [get, private set]
Will won't get the vaccine
Private Member Functions
void Update ()
bool FindSchool ()
void FindWorkPlace ()
void InfectOutside ()
bool CalculateIfHeGotInfected (VirusType virus)
void InfectInside ()
void Die ()
void DetectInfection ()
void Recovered ()
void GetNextMoveTarget ()
void DecideNextActionState ()
void CreatePaths ()
void MoveToMoveTarget ()
void MoveInWorldCellGrid ()
Moves the person in the world cell grid
Private Attributes
World world
Family family
Building occupationBuilding
Building currentBuilding
float time = float.MaxValue
ActionState currActionState = ActionState.RelaxingAtHome
float currActionTimeLeft = 0f
WorkTime workTime
VirusType currentlyInfectedBy
float recoveryTime = 0f
float immunityTime = 0f
float virusDiscoveryTime = 0f
bool willHeDie = false
float infectionAttempts = 0
List< Vector2 > pathToOccupation
List< Vector2 > pathFromOccupation
List< Vector2 > path
float moveTargetSwapInterval = 20f
bool generatedPath = false
short pathIndex = -1
Vector2 worldCellIndex
Detailed Description
A single worthless person
Definition at line 8 of file Person.cs.
Member Function Documentation
SetDefaultParameters()
void Person.SetDefaultParameters (World world, Family family, byte age) inline
Sets the person's initial states
Parameters
world Reference to the world class
family Reference to the person's family
Definition at line 94 of file Person.cs.
     {
         if (this.world == null && this.family == null)
         {
             this.world = world;
             this.family = family;
             this.Age = age;
             this.AgeGroup = age < 18 ? AgeGroup.Underage : AgeGroup.Adult;
         }
         else
             throw new Exception("Can't change world or family one of them is already set");
         this.worldCellIndex = new Vector2(XPos / world.CellSize, YPos / world.CellSize);
         this.world.AddPersonToWorldCell(worldCellIndex, this);
         this.Gender = (Gender)UnityEngine.Random.Range(0, 2);
         this.AntiVacination = UnityEngine.Random.Range(0f, 1f) <= Settings.AntiVacinationRate;
         //Decide occupation based on age
         if (Age < 18)
         {
             //If it didn't find a school try going to work
             if (!FindSchool())
             {
                 FindWorkPlace();
             }
             this.AgeCircle.color = Color.blue;
             this.AgeGroup = AgeGroup.Underage;
         }
         else
         {
             FindWorkPlace();
             this.AgeCircle.color = Color.magenta;
             this.AgeGroup = AgeGroup.Adult;
         }
         currActionTimeLeft = workTime.GetTimeTillWorkStart(world.dayTime);
         currentBuilding = family.House;
         currentBuilding.Enter(this);
         this.immunityTime = UnityEngine.Random.Range(-1036800, 2592000);
         world.IncreasePeople(AgeGroup);
         CreatePaths();
     }
References World.AddPersonToWorldCell(), Age, AntiVacination, Settings.AntiVacinationRate, World.CellSize, CreatePaths(), currActionTimeLeft, currentBuilding, World.dayTime, Building.Enter(), family, FindSchool(), FindWorkPlace(), Gender, WorkTime.GetTimeTillWorkStart(), Family.House, World.IncreasePeople(), workTime, world, worldCellIndex, XPos, and YPos.
Update()
void Person.Update () inline private
Definition at line 139 of file Person.cs.
     {
         //If the person is infected start recovering
         if (IsInfected)
         {
             //While the virus is still hiding
             if (virusDiscoveryTime > 0)
             {
                 virusDiscoveryTime -= Time.deltaTime * Settings.RealTimeToSimulationTime;
                 if (virusDiscoveryTime <= 0)
                 {
                     DetectInfection();
                 }
             }
             //When the virus has already been detected
             else
             {
                 //Start recovering
                 recoveryTime -= Time.deltaTime * Settings.RealTimeToSimulationTime;
                 if (recoveryTime <= 0f)
                 {
                     //If this was his destiny die
                     if (willHeDie)
                     {
                         Die();
                     }
                     else
                     {
                         Recovered();
                     }
                 }
             }
         }
         //Else decrease his/her immunity
         else
         {
             if (immunityTime > 0)
             {
                 immunityTime -= Time.deltaTime * Settings.RealTimeToSimulationTime;
             }
             if (infectionAttempts > 0f)
             {
                 infectionAttempts -= Time.deltaTime * Settings.InfectionRateInside * 0.01f;
             }
         }
         //Increase the timer by the elapsed time
         time += Time.deltaTime * Settings.RealTimeToSimulationTime;
         //If it's an action which doesn't require movement wait till the currActionTimeLeft goes to 0
         if (((byte)currActionState & 1) == 1)
         {
             if (IsInfected)
             {
                 if (time > Settings.InfectionRateInside)
                 {
                     InfectInside();
                     time = 0f;
                 }
             }
             currActionTimeLeft -= Time.deltaTime * Settings.RealTimeToSimulationTime;
             if (currActionTimeLeft <= 0f)
             {
                 DecideNextActionState();
             }
         }
         //Otherwise move
         else
         {
             if (time > moveTargetSwapInterval)
             {
                 GetNextMoveTarget();
                 MoveToMoveTarget();
                 time = 0f;
             }
         }
     }
References currActionState, currActionTimeLeft, DecideNextActionState(), DetectInfection(), Die(), GetNextMoveTarget(), immunityTime, InfectInside(), infectionAttempts, Settings.InfectionRateInside, IsInfected, moveTargetSwapInterval, MoveToMoveTarget(), Settings.RealTimeToSimulationTime, Recovered(), recoveryTime, time, virusDiscoveryTime, and willHeDie.
FindSchool()
bool Person.FindSchool () inline private
Definition at line 219 of file Person.cs.
     {
         occupationBuilding = world.GetOccupationBuilding((int)XPos, (int)YPos, BuildingType.School);
         if (occupationBuilding == null)
         {
             return false;
         }
         else
         {
             (occupationBuilding as School).NewStudent(this);
             workTime = new WorkTime(28800f);
             return true;
         }
     }
References World.GetOccupationBuilding(), occupationBuilding, School, workTime, world, XPos, and YPos.
Referenced by SetDefaultParameters().
FindWorkPlace()
void Person.FindWorkPlace () inline private
Definition at line 237 of file Person.cs.
     {
         occupationBuilding = world.GetOccupationBuilding((int)XPos, (int)YPos, BuildingType.WorkPlace);
         if (occupationBuilding == null)
         {
             Debug.Log("Can't find job");
         }
         else
         {
             Debug.Log("Found job");
             (occupationBuilding as WorkPlace).GiveJob(this);
             workTime = new WorkTime(Settings.PossibleWorkStartTimes[UnityEngine.Random.Range(0, Settings.PossibleWorkStartTimes.Length)]);
         }
     }
References World.GetOccupationBuilding(), occupationBuilding, Settings.PossibleWorkStartTimes, WorkPlace, workTime, world, XPos, and YPos.
Referenced by SetDefaultParameters().
InfectOutside()
void Person.InfectOutside () inline private
Definition at line 254 of file Person.cs.
     {
         this.world.InfectInRange(this.worldCellIndex, this.transform.position, currentlyInfectedBy);
     }
References currentlyInfectedBy, and World.InfectInRange().
Referenced by MoveToMoveTarget().
CalculateIfHeGotInfected()
bool Person.CalculateIfHeGotInfected (VirusType virus) inline private
Definition at line 261 of file Person.cs.
     {
         infectionAttempts += 1f * (IsInside ? 4f : 1f) * Settings.InfectionRateMultiplier * UnityEngine.Random.Range(0.5f, 5f);
         return infectionAttempts > virus.InfectionRate;
     }
References infectionAttempts, VirusType.InfectionRate, Settings.InfectionRateMultiplier, and IsInside.
Referenced by InfectedInRange().
InfectInside()
void Person.InfectInside () inline private
Definition at line 269 of file Person.cs.
     {
         currentBuilding.InfectInRange(this.transform.position, currentlyInfectedBy.RangeInsideBuilding, currentlyInfectedBy);
     }
References currentBuilding, currentlyInfectedBy, Building.InfectInRange(), and VirusType.RangeInsideBuilding.
Referenced by Update().
Die()
void Person.Die () inline private
Definition at line 276 of file Person.cs.
     {
         world.Died(this);
         family.KillPerson(this);
         this.gameObject.SetActive(false);
         GameObject.Destroy(this);
     }
References World.Died(), family, Family.KillPerson(), and world.
Referenced by Update().
Infectable()
bool Person.Infectable () inline
Checks if the person can be infected
Returns
true - it is possible, false - it is not possible
Definition at line 289 of file Person.cs.
     {
         return !this.IsInfected && immunityTime <= 0;
     }
References IsInfected.
DetectInfection()
void Person.DetectInfection () inline private
Definition at line 296 of file Person.cs.
     {
         //Make it so not everyone is a lawful citizen
         InQuarantine = UnityEngine.Random.Range(0, 10) <= 1;
         StatusCircle.color = Color.red;
         this.recoveryTime = currentlyInfectedBy.RecoveryTime * UnityEngine.Random.Range(1f - Settings.VirusVarience, 1f + Settings.VirusVarience);
         this.willHeDie = currentlyInfectedBy.DeathRate >= UnityEngine.Random.Range(0f, 1f);
     }
References currentlyInfectedBy, VirusType.DeathRate, InQuarantine, VirusType.RecoveryTime, StatusCircle, and Settings.VirusVarience.
Referenced by Update().
Recovered()
void Person.Recovered () inline private
Definition at line 307 of file Person.cs.
     {
         this.infectionAttempts = 0;
         this.IsInfected = false;
         this.immunityTime = currentlyInfectedBy.ImmunityTime * UnityEngine.Random.Range(1f - Settings.VirusVarience, 1f + Settings.VirusVarience);
         this.currentlyInfectedBy = null;
         this.StatusCircle.color = Color.green;
         this.InQuarantine = false;
         this.currActionState = ActionState.RelaxingAtHome;
         world.Recovered(AgeGroup);
         Debug.Log("Recovered");
     }
References currentlyInfectedBy, VirusType.ImmunityTime, InQuarantine, IsInfected, World.Recovered(), Settings.VirusVarience, and world.
Referenced by Update().
InfectedInRange()
void Person.InfectedInRange (VirusType virus) inline
This should be called when someone tries to infect him
Parameters
virus The type of virus he caught
Definition at line 325 of file Person.cs.
     {
         if (CalculateIfHeGotInfected(virus))
         {
             this.currentlyInfectedBy = virus;
             this.IsInfected = true;
             StatusCircle.color = Color.yellow;
             this.virusDiscoveryTime = virus.TimeToDiscover * UnityEngine.Random.Range(1f - Settings.VirusVarience, 1f + Settings.VirusVarience);
             world.Infected(AgeGroup);
         }
     }
References CalculateIfHeGotInfected(), World.Infected(), IsInfected, VirusType.TimeToDiscover, Settings.VirusVarience, and world.
StartingInfected()
void Person.StartingInfected (VirusType virus) inline
He is one of the many who rolled badly :(
Parameters
virus The type of virus he caught
Definition at line 342 of file Person.cs.
     {
         this.currentlyInfectedBy = virus;
         this.IsInfected = true;
         StatusCircle.color = Color.yellow;
         this.virusDiscoveryTime = virus.TimeToDiscover * UnityEngine.Random.Range(1f - Settings.VirusVarience, 1f + Settings.VirusVarience);
         world.Infected(AgeGroup);
     }
References World.Infected(), IsInfected, VirusType.TimeToDiscover, Settings.VirusVarience, and world.
GetNextMoveTarget()
void Person.GetNextMoveTarget () inline private
Definition at line 353 of file Person.cs.
     {
         //If the path is used up select a new one
         if (pathIndex < 0)
         {
             //If the move action ended select a new action
             if (generatedPath)
             {
                 DecideNextActionState();
                 generatedPath = false;
                 return;
             }
             GetPath(currActionState);
             pathIndex = (short)(path.Count - 1);
         }
         //If the person lives next to the target
         if (path.Count == 0)
         {
             nextMoveTarget = this.transform.position;
             return;
         }
         nextMoveTarget = path[pathIndex];
         pathIndex--;
     }
References currActionState, DecideNextActionState(), generatedPath, GetPath(), nextMoveTarget, path, and pathIndex.
Referenced by Update().
DecideNextActionState()
void Person.DecideNextActionState () inline private
Definition at line 384 of file Person.cs.
     {
         switch (currActionState)
         {
             case ActionState.RelaxingAtHome:
                 //If the world is currently in lockdown and the person's work isn't necessary for the society
                 if (Settings.Lockdown && !occupationBuilding.Necessary)
                 {
                     currActionState = ActionState.RelaxingAtHome;
                     currActionTimeLeft = Settings.RealTimeToSimulationTime * 4;
                 }
                 //If the person in quarantine
                 else if (InQuarantine)
                 {
                     currActionState = ActionState.InQuarantine;
                     currActionTimeLeft = recoveryTime;
                 }
                 //Go to work just as usual
                 else
                 {
                     currActionState = ActionState.GoingToWork;
                     currentBuilding.Leave(this);
                 }
                 break;
             case ActionState.Waiting:
                 break;
             case ActionState.GoingToWork:
                 currActionTimeLeft = workTime.GetActionTime();
                 currActionState = ActionState.Working;
                 currentBuilding = occupationBuilding;
                 currentBuilding.Enter(this);
                 break;
             case ActionState.Working:
                 currActionState = ActionState.GoingHome;
                 currentBuilding.Leave(this);
                 break;
             case ActionState.GoingShopping:
                 currentBuilding = family.FavoriteMarket;
                 currActionTimeLeft = 3600f;
                 currActionState = ActionState.Shopping;
                 currentBuilding.Enter(this);
                 break;
             case ActionState.Shopping:
                 currActionState = ActionState.GoingHomeFromShopping;
                 currentBuilding.Leave(this);
                 break;
             case ActionState.GoingHomeFromShopping:
                 if (InQuarantine)
                 {
                     currActionState = ActionState.InQuarantine;
                     currActionTimeLeft = recoveryTime;
                 }
                 else
                 {
                     currActionState = ActionState.RelaxingAtHome;
                     currActionTimeLeft = workTime.GetTimeTillWorkStart(world.dayTime);
                 }
                 family.GotSuppliesFromShop();
                 currentBuilding = family.House;
                 currentBuilding.Enter(this);
                 break;
             case ActionState.GoingHome:
                 if (InQuarantine)
                 {
                     currActionState = ActionState.InQuarantine;
                     currActionTimeLeft = recoveryTime;
                 }
                 else
                 {
                     currActionState = ActionState.RelaxingAtHome;
                     currActionTimeLeft = workTime.GetTimeTillWorkStart(world.dayTime);
                 }
                 currentBuilding = family.House;
                 currentBuilding.Enter(this);
                 break;
             default:
                 break;
         }
     }
References currActionState, currActionTimeLeft, currentBuilding, World.dayTime, Building.Enter(), family, Family.FavoriteMarket, WorkTime.GetActionTime(), WorkTime.GetTimeTillWorkStart(), Family.GotSuppliesFromShop(), Family.House, InQuarantine, Building.Leave(), Settings.Lockdown, Building.Necessary, occupationBuilding, Settings.RealTimeToSimulationTime, recoveryTime, workTime, and world.
Referenced by GetNextMoveTarget(), and Update().
CreatePaths()
void Person.CreatePaths () inline private
Definition at line 475 of file Person.cs.
     {
         world.CreatePath(out pathFromOccupation, occupationBuilding.NearestRoad, family.HouseEnteraceLoc);
         pathFromOccupation.Insert(0, new Vector2(family.HouseLoc.x + UnityEngine.Random.Range(-0.5f, 0.5f), family.HouseLoc.y + UnityEngine.Random.Range(-0.5f, 0.5f)));
         world.CreatePath(out pathToOccupation, family.HouseEnteraceLoc, occupationBuilding.NearestRoad);
         pathToOccupation.Insert(0, new Vector2(occupationBuilding.transform.position.x + UnityEngine.Random.Range(-0.5f, 0.5f), occupationBuilding.transform.position.y + UnityEngine.Random.Range(-0.5f, 0.5f)));
     }
References World.CreatePath(), family, Family.HouseEnteraceLoc, Family.HouseLoc, Building.NearestRoad, occupationBuilding, pathFromOccupation, pathToOccupation, and world.
Referenced by SetDefaultParameters().
GetPath()
void Person.GetPath (ActionState nextActionState) inline
Definition at line 486 of file Person.cs.
     {
         generatedPath = true;
         switch (nextActionState)
         {
             case ActionState.GoingHome:
                 path = pathFromOccupation;
                 break;
             case ActionState.GoingToWork:
                 path = pathToOccupation;
                 break;
             case ActionState.GoingShopping:
                 path = family.pathToShop;
                 break;
             case ActionState.GoingHomeFromShopping:
                 path = family.pathFromShop;
                 break;
             default:
                 break;
         }
         if (path == null)
         {
             Debug.Log("Can't find path");
             currActionState = ActionState.Waiting;
             nextMoveTarget = this.transform.position;
             this.gameObject.SetActive(false);
         }
     }
References currActionState, family, generatedPath, nextMoveTarget, path, pathFromOccupation, Family.pathFromShop, pathToOccupation, and Family.pathToShop.
Referenced by GetNextMoveTarget().
SendToTheShop()
bool Person.SendToTheShop () inline
Tries to send this person to the shop
Returns
True if the person accepts false if he/she refuses
Definition at line 527 of file Person.cs.
     {
         if (this.currActionState != ActionState.RelaxingAtHome && this.currActionTimeLeft >= 10800f)
         {
             return false;
         }
         this.currActionState = ActionState.GoingShopping;
         return true;
     }
GetVaccinated()
void Person.GetVaccinated () inline
The person gets vaccinated
Definition at line 541 of file Person.cs.
     {
         this.immunityTime = Settings.VaccineImmunityTime;
         Debug.Log("Got vaccinated");
     }
References Settings.VaccineImmunityTime.
MoveToMoveTarget()
void Person.MoveToMoveTarget () inline private
Definition at line 549 of file Person.cs.
     {
         if ((byte)currActionState % 2 == 0)
         {
             // this.transform.position = Vector2.Lerp(this.transform.position, nextMoveTarget, time);
             this.transform.position = nextMoveTarget;
             if (IsInfected)
                 InfectOutside();
             MoveInWorldCellGrid();
         }
     }
References currActionState, InfectOutside(), IsInfected, MoveInWorldCellGrid(), and nextMoveTarget.
Referenced by Update().
MoveInWorldCellGrid()
void Person.MoveInWorldCellGrid () inline private
Moves the person in the world cell grid
Definition at line 566 of file Person.cs.
     {
         Vector2 newWorldCellIndex = new Vector2(XPos / world.CellSize, YPos / world.CellSize);
         world.MovePerson(worldCellIndex, newWorldCellIndex, this);
         worldCellIndex = newWorldCellIndex;
     }
References World.CellSize, World.MovePerson(), world, worldCellIndex, XPos, and YPos.
Referenced by MoveToMoveTarget().
Member Data Documentation
AgeCircle
SpriteRenderer Person.AgeCircle
Definition at line 11 of file Person.cs.
StatusCircle
SpriteRenderer Person.StatusCircle
Definition at line 14 of file Person.cs.
Referenced by DetectInfection().
world
World Person.world private
Definition at line 62 of file Person.cs.
Referenced by CreatePaths(), DecideNextActionState(), Die(), FindSchool(), FindWorkPlace(), InfectedInRange(), MoveInWorldCellGrid(), Recovered(), SetDefaultParameters(), and StartingInfected().
family
Family Person.family private
Definition at line 63 of file Person.cs.
Referenced by CreatePaths(), DecideNextActionState(), Die(), GetPath(), and SetDefaultParameters().
occupationBuilding
Building Person.occupationBuilding private
Definition at line 64 of file Person.cs.
Referenced by CreatePaths(), DecideNextActionState(), FindSchool(), and FindWorkPlace().
currentBuilding
Building Person.currentBuilding private
Definition at line 65 of file Person.cs.
Referenced by DecideNextActionState(), InfectInside(), and SetDefaultParameters().
time
float Person.time = float.MaxValue private
Definition at line 66 of file Person.cs.
Referenced by Update().
currActionState
ActionState Person.currActionState = ActionState.RelaxingAtHome private
Definition at line 67 of file Person.cs.
Referenced by DecideNextActionState(), GetNextMoveTarget(), GetPath(), MoveToMoveTarget(), and Update().
currActionTimeLeft
float Person.currActionTimeLeft = 0f private
Definition at line 68 of file Person.cs.
Referenced by DecideNextActionState(), SetDefaultParameters(), and Update().
workTime
WorkTime Person.workTime private
Definition at line 69 of file Person.cs.
Referenced by DecideNextActionState(), FindSchool(), FindWorkPlace(), and SetDefaultParameters().
currentlyInfectedBy
VirusType Person.currentlyInfectedBy private
Definition at line 70 of file Person.cs.
Referenced by DetectInfection(), InfectInside(), InfectOutside(), and Recovered().
recoveryTime
float Person.recoveryTime = 0f private
Definition at line 71 of file Person.cs.
Referenced by DecideNextActionState(), and Update().
immunityTime
float Person.immunityTime = 0f private
Definition at line 72 of file Person.cs.
Referenced by Update().
virusDiscoveryTime
float Person.virusDiscoveryTime = 0f private
Definition at line 73 of file Person.cs.
Referenced by Update().
willHeDie
bool Person.willHeDie = false private
Definition at line 74 of file Person.cs.
Referenced by Update().
infectionAttempts
float Person.infectionAttempts = 0 private
Definition at line 75 of file Person.cs.
Referenced by CalculateIfHeGotInfected(), and Update().
nextMoveTarget
Vector2 Person.nextMoveTarget
Definition at line 79 of file Person.cs.
Referenced by GetNextMoveTarget(), GetPath(), and MoveToMoveTarget().
pathToOccupation
List<Vector2> Person.pathToOccupation private
Definition at line 80 of file Person.cs.
Referenced by CreatePaths(), and GetPath().
pathFromOccupation
List<Vector2> Person.pathFromOccupation private
Definition at line 81 of file Person.cs.
Referenced by CreatePaths(), and GetPath().
path
List<Vector2> Person.path private
Definition at line 82 of file Person.cs.
Referenced by GetNextMoveTarget(), and GetPath().
moveTargetSwapInterval
float Person.moveTargetSwapInterval = 20f private
Definition at line 83 of file Person.cs.
Referenced by Update().
generatedPath
bool Person.generatedPath = false private
Definition at line 84 of file Person.cs.
Referenced by GetNextMoveTarget(), and GetPath().
pathIndex
short Person.pathIndex = -1 private
Definition at line 85 of file Person.cs.
Referenced by GetNextMoveTarget().
worldCellIndex
Vector2 Person.worldCellIndex private
Definition at line 86 of file Person.cs.
Referenced by MoveInWorldCellGrid(), and SetDefaultParameters().
Property Documentation
Age
byte Person.Age get private set
The age of the person This will determine his occupation mostly
Definition at line 20 of file Person.cs.
 { get; private set; }
Referenced by SetDefaultParameters().
AgeGroup
AgeGroup Person.AgeGroup get private set
What age group does he belongs to
Definition at line 25 of file Person.cs.
 { get; private set; }
Referenced by World.Died().
Gender
Gender Person.Gender get private set
The gender of the person
Definition at line 30 of file Person.cs.
 { get; private set; }
Referenced by SetDefaultParameters().
XPos
float Person.XPos get
The person's position on the x axis
Definition at line 35 of file Person.cs.
 { get => this.transform.position.x; }
Referenced by FindSchool(), FindWorkPlace(), MoveInWorldCellGrid(), and SetDefaultParameters().
YPos
float Person.YPos get
The person's position on the y axis
Definition at line 40 of file Person.cs.
 { get => this.transform.position.y; }
Referenced by FindSchool(), FindWorkPlace(), MoveInWorldCellGrid(), and SetDefaultParameters().
IsInfected
bool Person.IsInfected = false get private set
Is the person infected
Definition at line 45 of file Person.cs.
 { get; private set; } = false;
Referenced by World.Died(), Infectable(), InfectedInRange(), MoveToMoveTarget(), Recovered(), StartingInfected(), and Update().
InQuarantine
bool Person.InQuarantine = false get private set
Is the person in quarantine
Definition at line 50 of file Person.cs.
 { get; private set; } = false;
Referenced by DecideNextActionState(), DetectInfection(), and Recovered().
IsInside
bool Person.IsInside get
Is the person inside a building
Definition at line 55 of file Person.cs.
 { get => (byte)currActionState % 2 == 1; }
Referenced by CalculateIfHeGotInfected().
AntiVacination
bool Person.AntiVacination get private set
Will won't get the vaccine
Definition at line 60 of file Person.cs.
 { get; private set; }
Referenced by SetDefaultParameters().
The documentation for this class was generated from the following file:
Assets/Scripts/Agent/Person.cs