Bomberman: PathMaker Class Reference
PathMaker Class Reference
Classes
class Node
Each cell in the grid is a node
Public Member Functions
PathMaker (short size, World world)
Creates a new instance of the PathMaker
bool CreatePath (out List< Vector2 > moveTargetList, Vector2 startCoord, Vector2 goalCoord)
Creates a new path
Private Member Functions
void ResetBack ()
Resets the goal and start back to what it should be and reverses the visited nodes state to not visited
bool CheckIfValid (Node node)
bool SearchForGoal (Node current, short depth)
Private Attributes
Node[,] map
World world
List< Vector2 > path
Node start
Node goal
short size
Stack< Node > visitedNodes = new Stack<Node>()
Static Private Attributes
const short maxDepth = 1024
Detailed Description
Definition at line 5 of file PathMaker.cs.
Constructor & Destructor Documentation
PathMaker()
PathMaker.PathMaker (short size, World world) inline
Creates a new instance of the PathMaker
Parameters
start The starting position
goal The target's position
size The size of the grid (x size = Size *2, y size = Size*2)
world The world it is in
Definition at line 98 of file PathMaker.cs.
     {
         this.world = world;
         this.size = size;
         map = new Node[world.XSize, world.YSize];
         //Fill in the grid
         for (short i = 0; i < map.GetLength(0); i++)
         {
             for (short j = 0; j < map.GetLength(1); j++)
             {
                 map[i, j] = new Node(new short[] { i, j }, i, j, world.Cells[i, j] == CellType.Road);
             }
         }
     }
References World.Cells, map, size, world, World.XSize, and World.YSize.
Member Function Documentation
ResetBack()
void PathMaker.ResetBack () inline private
Resets the goal and start back to what it should be and reverses the visited nodes state to not visited
Definition at line 117 of file PathMaker.cs.
     {
         while (visitedNodes.Count != 0)
         {
             visitedNodes.Pop().Visited = false;
         }
         start.Reset(true);
         goal.Reset(true);
     }
References goal, PathMaker.Node.Reset(), start, and visitedNodes.
Referenced by CreatePath().
CreatePath()
bool PathMaker.CreatePath (out List< Vector2 > moveTargetList, Vector2 startCoord, Vector2 goalCoord) inline
Creates a new path
Parameters
moveTargetList The stack which will store the coord toward the target
Returns
False if there can't be a path made True if it was a success
Definition at line 134 of file PathMaker.cs.
     {
         //  Set the goal and the start
         this.goal = map[(int)goalCoord.y, (int)goalCoord.x];
         this.goal.passable = true; //If it is water make it passable (maybe someday I will make this better)
         this.start = map[(int)startCoord.y, (int)startCoord.x];
         path = new List<Vector2>();
         //Search for the goal
         if (!SearchForGoal(start, 0))
         {
             moveTargetList = path;
             ResetBack();
             return false;
         }
         moveTargetList = path;
         ResetBack();
         return true;
     }
References map, PathMaker.Node.passable, path, ResetBack(), SearchForGoal(), and start.
Referenced by World.CreatePath().
CheckIfValid()
bool PathMaker.CheckIfValid (Node node) inline private
Definition at line 156 of file PathMaker.cs.
     {
         return node.passable && !node.Visited;
     }
References PathMaker.Node.passable, and PathMaker.Node.Visited.
Referenced by SearchForGoal().
SearchForGoal()
bool PathMaker.SearchForGoal (Node current, short depth) inline private
Definition at line 164 of file PathMaker.cs.
     {
         current.Visit(); //Visit the node
         visitedNodes.Push(current);
         //Check if it is the goal
         if (current.Equals(goal))
         {
             return true;
         }
         //So it doesn't make a path which kills the animal in the process
         if (depth >= maxDepth)
         {
             return false;
         }
         //Get the possible ways it can go
         List<Node> possibleWays = new List<Node>();
         if (current.indices[0] - 1 >= 0 && CheckIfValid(map[current.indices[0] - 1, current.indices[1]]))
         {
             possibleWays.Add(map[current.indices[0] - 1, current.indices[1]]);
         }
         if (current.indices[1] - 1 >= 0 && CheckIfValid(map[current.indices[0], current.indices[1] - 1]))
         {
             possibleWays.Add(map[current.indices[0], current.indices[1] - 1]);
         }
         if (current.indices[0] + 1 < map.GetLength(0) && CheckIfValid(map[current.indices[0] + 1, current.indices[1]]))
         {
             possibleWays.Add(map[current.indices[0] + 1, current.indices[1]]);
         }
         if (current.indices[1] + 1 < map.GetLength(1) && CheckIfValid(map[current.indices[0], current.indices[1] + 1]))
         {
             possibleWays.Add(map[current.indices[0], current.indices[1] + 1]);
         }
         //Calculate their distance from the goal
         for (int i = 0; i < possibleWays.Count; i++)
         {
             possibleWays[i].SetDist(World.CalcDistance(goal.position, possibleWays[i].position));
         }
         //Order them by the distance and try them each
         foreach (var item in possibleWays.OrderBy(x => x.DistanceFromGoal))
         {
             if (SearchForGoal(item, (short)(depth + 1)))
             {
                 path.Add(new Vector2(item.position.y, item.position.x));
                 return true;
             }
         }
         //If none of the ways were good return false
         return false;
     }
References World.CalcDistance(), CheckIfValid(), goal, PathMaker.Node.indices, map, maxDepth, path, PathMaker.Node.position, PathMaker.Node.Visit(), and visitedNodes.
Referenced by CreatePath().
Member Data Documentation
maxDepth
const short PathMaker.maxDepth = 1024 static private
Definition at line 82 of file PathMaker.cs.
Referenced by SearchForGoal().
map
Node [,] PathMaker.map private
Definition at line 83 of file PathMaker.cs.
Referenced by CreatePath(), PathMaker(), and SearchForGoal().
world
World PathMaker.world private
Definition at line 84 of file PathMaker.cs.
Referenced by PathMaker().
path
List<Vector2> PathMaker.path private
Definition at line 85 of file PathMaker.cs.
Referenced by CreatePath(), and SearchForGoal().
start
Node PathMaker.start private
Definition at line 86 of file PathMaker.cs.
Referenced by CreatePath(), and ResetBack().
goal
Node PathMaker.goal private
Definition at line 87 of file PathMaker.cs.
Referenced by ResetBack(), and SearchForGoal().
size
short PathMaker.size private
Definition at line 88 of file PathMaker.cs.
Referenced by PathMaker().
visitedNodes
Stack<Node> PathMaker.visitedNodes = new Stack<Node>() private
Definition at line 89 of file PathMaker.cs.
Referenced by ResetBack(), and SearchForGoal().
The documentation for this class was generated from the following file:
Assets/Scripts/Map/PathMaker.cs