Bomberman: StatusHandler Class Reference
StatusHandler Class Reference
Handles the status informations Also updates the labels if necessary
Public Member Functions
void InitStatus ()
Inits the status's properties
void IncreasePeople (AgeGroup ageGrp)
Increases the number of people in the specified age group
void DecreasePeople (AgeGroup ageGrp)
Decreases the number of people in the specified age group
void StatusButtonClick ()
Hides or Shows the canvas of the statuses
void UpdateDayTime (int dayCount)
Updates the day time
void IncreaseInfectedCount (AgeGroup ageGrp)
Increase infected count in the specified age group
void DecreaseInfectedCount (AgeGroup ageGrp)
Decrease infected count in the specified age group
void UpdateLockDownState ()
Updates the lockdown text
override string ToString ()
Writes out every status varriable in a string separated by a ';'
Public Attributes
Text DayCountText
Text LockDownText
Text PeopleCountText
Text UnderagePeopleCountText
Text AdultPeopleCountText
Text InfectedCountText
Text UnderageInfectedText
Text AdultInfectedText
Properties
int InitialPeopleCount = 0 [get, private set]
Private Member Functions
void UpdatePeopleCount ()
void UpdateUnderAgePeopleCount ()
void UpdateAdultPeopleCount ()
void UpdateInfectedCount ()
void UpdateUnderAgeInfectedCount ()
void UpdateAdultInfectedCount ()
Private Attributes
GraphWindow graph
int dayCounter = 0
int initialAdultPeopleCount = 0
int adultPeopleCount = 0
int initialUnderagePeopleCount = 0
int underagePeopleCount = 0
int infectedCount = 0
int underAgeInfectedCount = 0
int adultInfectedCount = 0
int currPeople = 0
Detailed Description
Handles the status informations Also updates the labels if necessary
Definition at line 8 of file StatusHandler.cs.
Member Function Documentation
InitStatus()
void StatusHandler.InitStatus () inline
Inits the status's properties
Definition at line 52 of file StatusHandler.cs.
     {
         InitialPeopleCount = adultPeopleCount + underagePeopleCount;
         initialAdultPeopleCount = adultPeopleCount;
         initialUnderagePeopleCount = underagePeopleCount;
         UpdatePeopleCount();
         graph.InitGraph(InitialPeopleCount);
         graph.AddValue(infectedCount);
     }
References GraphWindow.AddValue(), adultPeopleCount, graph, infectedCount, GraphWindow.InitGraph(), initialAdultPeopleCount, InitialPeopleCount, initialUnderagePeopleCount, underagePeopleCount, and UpdatePeopleCount().
Referenced by World.Awake().
IncreasePeople()
void StatusHandler.IncreasePeople (AgeGroup ageGrp) inline
Increases the number of people in the specified age group
Parameters
ageGrp Which group to increase
Definition at line 67 of file StatusHandler.cs.
     {
         switch (ageGrp)
         {
             case AgeGroup.Underage:
                 underagePeopleCount++;
                 break;
             case AgeGroup.Adult:
                 adultPeopleCount++;
                 break;
             default:
                 break;
         }
         currPeople++;
     }
References adultPeopleCount, currPeople, and underagePeopleCount.
Referenced by World.IncreasePeople().
DecreasePeople()
void StatusHandler.DecreasePeople (AgeGroup ageGrp) inline
Decreases the number of people in the specified age group
Parameters
ageGrp Which group to increase
Definition at line 90 of file StatusHandler.cs.
     {
         switch (ageGrp)
         {
             case AgeGroup.Underage:
                 underagePeopleCount--;
                 break;
             case AgeGroup.Adult:
                 adultPeopleCount--;
                 break;
             default:
                 break;
         }
         currPeople--;
         //Update the texts
         UpdatePeopleCount();
     }
References adultPeopleCount, currPeople, underagePeopleCount, and UpdatePeopleCount().
Referenced by World.Died().
StatusButtonClick()
void StatusHandler.StatusButtonClick () inline
Hides or Shows the canvas of the statuses
Definition at line 114 of file StatusHandler.cs.
     {
         this.gameObject.SetActive(!this.gameObject.activeSelf);
     }
UpdateDayTime()
void StatusHandler.UpdateDayTime (int dayCount) inline
Updates the day time
Parameters
dayCount
Definition at line 124 of file StatusHandler.cs.
     {
         DayCountText.text = $"Day: {dayCount}";
         this.dayCounter = dayCount;
         graph.AddValue(infectedCount);
     }
References GraphWindow.AddValue(), DayCountText, graph, and infectedCount.
Referenced by World.Update().
UpdatePeopleCount()
void StatusHandler.UpdatePeopleCount () inline private
Definition at line 133 of file StatusHandler.cs.
     {
         PeopleCountText.text = $"People: {currPeople}/{InitialPeopleCount}";
         UpdateInfectedCount();
         UpdateAdultPeopleCount();
         UpdateUnderAgePeopleCount();
     }
References PeopleCountText, UpdateAdultPeopleCount(), UpdateInfectedCount(), and UpdateUnderAgePeopleCount().
Referenced by DecreasePeople(), and InitStatus().
UpdateUnderAgePeopleCount()
void StatusHandler.UpdateUnderAgePeopleCount () inline private
Definition at line 143 of file StatusHandler.cs.
     {
         this.UnderagePeopleCountText.text = $"Underage people: {underagePeopleCount}/{initialUnderagePeopleCount}";
     }
Referenced by UpdatePeopleCount().
UpdateAdultPeopleCount()
void StatusHandler.UpdateAdultPeopleCount () inline private
Definition at line 150 of file StatusHandler.cs.
     {
         this.AdultPeopleCountText.text = $"Adult people: {adultPeopleCount}/{initialAdultPeopleCount}";
     }
Referenced by UpdatePeopleCount().
UpdateInfectedCount()
void StatusHandler.UpdateInfectedCount () inline private
Definition at line 157 of file StatusHandler.cs.
     {
         InfectedCountText.text = $"Infected people: {infectedCount}/{currPeople}";
         UpdateUnderAgeInfectedCount();
         UpdateAdultInfectedCount();
     }
References InfectedCountText, UpdateAdultInfectedCount(), and UpdateUnderAgeInfectedCount().
Referenced by DecreaseInfectedCount(), IncreaseInfectedCount(), and UpdatePeopleCount().
UpdateUnderAgeInfectedCount()
void StatusHandler.UpdateUnderAgeInfectedCount () inline private
Definition at line 166 of file StatusHandler.cs.
     {
         this.UnderageInfectedText.text = $"Underage infected: {underAgeInfectedCount}/{underagePeopleCount}";
     }
Referenced by UpdateInfectedCount().
UpdateAdultInfectedCount()
void StatusHandler.UpdateAdultInfectedCount () inline private
Definition at line 173 of file StatusHandler.cs.
     {
         this.AdultInfectedText.text = $"Adult infected: {adultInfectedCount}/{adultPeopleCount}";
     }
Referenced by UpdateInfectedCount().
IncreaseInfectedCount()
void StatusHandler.IncreaseInfectedCount (AgeGroup ageGrp) inline
Increase infected count in the specified age group
Parameters
ageGrp Which group to increase
Definition at line 183 of file StatusHandler.cs.
     {
         this.infectedCount++;
         switch (ageGrp)
         {
             case AgeGroup.Underage:
                 underAgeInfectedCount++;
                 break;
             case AgeGroup.Adult:
                 adultInfectedCount++;
                 break;
             default:
                 break;
         }
         UpdateInfectedCount();
     }
References adultInfectedCount, underAgeInfectedCount, and UpdateInfectedCount().
Referenced by World.Infected().
DecreaseInfectedCount()
void StatusHandler.DecreaseInfectedCount (AgeGroup ageGrp) inline
Decrease infected count in the specified age group
Parameters
ageGrp Which group to decrease
Definition at line 207 of file StatusHandler.cs.
     {
         this.infectedCount--;
         switch (ageGrp)
         {
             case AgeGroup.Underage:
                 underAgeInfectedCount--;
                 break;
             case AgeGroup.Adult:
                 adultInfectedCount--;
                 break;
             default:
                 break;
         }
         UpdateInfectedCount();
     }
References adultInfectedCount, underAgeInfectedCount, and UpdateInfectedCount().
Referenced by World.Died(), and World.Recovered().
UpdateLockDownState()
void StatusHandler.UpdateLockDownState () inline
Updates the lockdown text
Definition at line 231 of file StatusHandler.cs.
     {
         LockDownText.text = $"Lockdown {(Settings.Lockdown ? "on" : "off")}";
     }
References LockDownText.
ToString()
override string StatusHandler.ToString () inline
Writes out every status varriable in a string separated by a ';'
Returns
The string
Definition at line 241 of file StatusHandler.cs.
     {
         return $"{dayCounter}" +
             $";{currPeople}" +
             $";{underagePeopleCount}" +
             $";{adultPeopleCount}" +
             $";{infectedCount}" +
             $";{underAgeInfectedCount}" +
             $";{adultInfectedCount}" +
             $";{(Settings.Lockdown ? "on" : "off")}";
     }
Referenced by World.WriteOutDailyData().
Member Data Documentation
DayCountText
Text StatusHandler.DayCountText
Definition at line 11 of file StatusHandler.cs.
Referenced by UpdateDayTime().
LockDownText
Text StatusHandler.LockDownText
Definition at line 14 of file StatusHandler.cs.
Referenced by UpdateLockDownState().
PeopleCountText
Text StatusHandler.PeopleCountText
Definition at line 17 of file StatusHandler.cs.
Referenced by UpdatePeopleCount().
UnderagePeopleCountText
Text StatusHandler.UnderagePeopleCountText
Definition at line 20 of file StatusHandler.cs.
AdultPeopleCountText
Text StatusHandler.AdultPeopleCountText
Definition at line 23 of file StatusHandler.cs.
InfectedCountText
Text StatusHandler.InfectedCountText
Definition at line 26 of file StatusHandler.cs.
Referenced by UpdateInfectedCount().
UnderageInfectedText
Text StatusHandler.UnderageInfectedText
Definition at line 29 of file StatusHandler.cs.
AdultInfectedText
Text StatusHandler.AdultInfectedText
Definition at line 32 of file StatusHandler.cs.
graph
GraphWindow StatusHandler.graph private
Definition at line 35 of file StatusHandler.cs.
Referenced by InitStatus(), and UpdateDayTime().
dayCounter
int StatusHandler.dayCounter = 0 private
Definition at line 37 of file StatusHandler.cs.
initialAdultPeopleCount
int StatusHandler.initialAdultPeopleCount = 0 private
Definition at line 39 of file StatusHandler.cs.
Referenced by InitStatus().
adultPeopleCount
int StatusHandler.adultPeopleCount = 0 private
Definition at line 40 of file StatusHandler.cs.
Referenced by DecreasePeople(), IncreasePeople(), and InitStatus().
initialUnderagePeopleCount
int StatusHandler.initialUnderagePeopleCount = 0 private
Definition at line 41 of file StatusHandler.cs.
Referenced by InitStatus().
underagePeopleCount
int StatusHandler.underagePeopleCount = 0 private
Definition at line 42 of file StatusHandler.cs.
Referenced by DecreasePeople(), IncreasePeople(), and InitStatus().
infectedCount
int StatusHandler.infectedCount = 0 private
Definition at line 43 of file StatusHandler.cs.
Referenced by InitStatus(), and UpdateDayTime().
underAgeInfectedCount
int StatusHandler.underAgeInfectedCount = 0 private
Definition at line 44 of file StatusHandler.cs.
Referenced by DecreaseInfectedCount(), and IncreaseInfectedCount().
adultInfectedCount
int StatusHandler.adultInfectedCount = 0 private
Definition at line 45 of file StatusHandler.cs.
Referenced by DecreaseInfectedCount(), and IncreaseInfectedCount().
currPeople
int StatusHandler.currPeople = 0 private
Definition at line 46 of file StatusHandler.cs.
Referenced by DecreasePeople(), and IncreasePeople().
Property Documentation
InitialPeopleCount
int StatusHandler.InitialPeopleCount = 0 get private set
Definition at line 38 of file StatusHandler.cs.
 { get; private set; } = 0; //The starting number of people
Referenced by InitStatus().
The documentation for this class was generated from the following file:
Assets/Scripts/Menus/StatusHandler.cs