Bomberman: WorldCell Class Reference
WorldCell Class Reference
A bigger cell
Public Member Functions
WorldCell (int xIndex, int yIndex)
Creates a new world cell
Building GetAvalibleBuilding (BuildingType buildingType)
Returns an avalible building
void AddBuilding (Building building)
Adds a building to the cell
void AddPerson (Person personToAdd)
Adds a person to the cell
void RemovePerson (Person personToRemove)
Remove the person from the cell
List< Person > GetEveryPersonInTheCell ()
Returns a list of every person in the cell
void TryToInfectEveryOneInRange (UnityEngine.Vector2 source, VirusType virus)
Tries to infect everyone who is on the same cell
Properties
int NumberOfPeopleInTheCell [get]
How many people are in the cell
int XIndex [get, private set]
The cell's x index
int YIndex [get, private set]
The cell's y index
Private Attributes
List< Person > persons
List< Building > BuildingsInCell
Detailed Description
A bigger cell
Definition at line 7 of file WorldCell.cs.
Constructor & Destructor Documentation
WorldCell()
WorldCell.WorldCell (int xIndex, int yIndex) inline
Creates a new world cell
Parameters
xIndex The cell's x index
yIndex The cell's y index
Definition at line 33 of file WorldCell.cs.
     {
         persons = new List<Person>();
         BuildingsInCell = new List<Building>();
         this.XIndex = xIndex;
         this.YIndex = yIndex;
     }
References BuildingsInCell, persons, XIndex, and YIndex.
Member Function Documentation
GetAvalibleBuilding()
Building WorldCell.GetAvalibleBuilding (BuildingType buildingType) inline
Returns an avalible building
Parameters
buildingType The type of the building
Returns
Reference to the building
Definition at line 47 of file WorldCell.cs.
     {
         return BuildingsInCell.Find(x => x.BuildingType == buildingType && x.HasFreeSpace());
     }
References BuildingsInCell.
Referenced by World.LookForBuilding().
AddBuilding()
void WorldCell.AddBuilding (Building building) inline
Adds a building to the cell
Parameters
building The building which should be added
Definition at line 57 of file WorldCell.cs.
     {
         BuildingsInCell.Add(building);
     }
References BuildingsInCell.
Referenced by WorldGenerator.GenerateBuildings().
AddPerson()
void WorldCell.AddPerson (Person personToAdd) inline
Adds a person to the cell
Parameters
personToAdd The person who should be added
Definition at line 67 of file WorldCell.cs.
     {
         persons.Add(personToAdd);
     }
References persons.
Referenced by World.AddPersonToWorldCell(), and World.MovePerson().
RemovePerson()
void WorldCell.RemovePerson (Person personToRemove) inline
Remove the person from the cell
Parameters
personToRemove The person who should be removed
Definition at line 77 of file WorldCell.cs.
     {
         persons.Remove(personToRemove);
     }
References persons.
Referenced by World.MovePerson().
GetEveryPersonInTheCell()
List<Person> WorldCell.GetEveryPersonInTheCell () inline
Returns a list of every person in the cell
Returns
The list (deep copy)
Definition at line 87 of file WorldCell.cs.
     {
         return persons.Select(x => x).ToList();
     }
References persons.
TryToInfectEveryOneInRange()
void WorldCell.TryToInfectEveryOneInRange (UnityEngine.Vector2 source, VirusType virus) inline
Tries to infect everyone who is on the same cell
Parameters
source The source of the virus
virus The type of the virus
Definition at line 97 of file WorldCell.cs.
     {
         for (int i = 0; i < persons.Count; i++)
         {
             if (persons[i].Infectable() && source.Equals(persons[i].transform.position))
             {
                 persons[i].InfectedInRange(virus);
             }
         }
     }
References persons.
Referenced by World.InfectInRange().
Member Data Documentation
persons
List<Person> WorldCell.persons private
Definition at line 9 of file WorldCell.cs.
Referenced by AddPerson(), GetEveryPersonInTheCell(), RemovePerson(), TryToInfectEveryOneInRange(), and WorldCell().
BuildingsInCell
List<Building> WorldCell.BuildingsInCell private
Definition at line 10 of file WorldCell.cs.
Referenced by AddBuilding(), GetAvalibleBuilding(), and WorldCell().
Property Documentation
NumberOfPeopleInTheCell
int WorldCell.NumberOfPeopleInTheCell get
How many people are in the cell
Definition at line 15 of file WorldCell.cs.
 { get => persons.Count; }
XIndex
int WorldCell.XIndex get private set
The cell's x index
Definition at line 20 of file WorldCell.cs.
 { get; private set; }
Referenced by WorldCell().
YIndex
int WorldCell.YIndex get private set
The cell's y index
Definition at line 25 of file WorldCell.cs.
 { get; private set; }
Referenced by WorldCell().
The documentation for this class was generated from the following file:
Assets/Scripts/DataTypes/WorldCell.cs