Bomberman: WorkTime Struct Reference
WorkTime Struct Reference
Stores the work time of a person
Public Member Functions
WorkTime (float startTime)
Creates a new work time object with a 8 hour long shift
float GetActionTime ()
Gets the length of the shift
float GetTimeTillWorkStart (float currTime)
Returns the time remaining until the start of the shift
Properties
float StartTime [get, private set]
When his shift starts
float EndTime [get, private set]
When his shift ends
Private Attributes
float actionTime
Detailed Description
Stores the work time of a person
Definition at line 4 of file WorkTime.cs.
Constructor & Destructor Documentation
WorkTime()
WorkTime.WorkTime (float startTime) inline
Creates a new work time object with a 8 hour long shift
Parameters
startTime
Definition at line 24 of file WorkTime.cs.
     {
         this.StartTime = startTime;
         this.EndTime = (startTime + 3600 * 8) % 86400;
         this.actionTime = (EndTime - StartTime + 86400) % 86400;
     }
References EndTime, and StartTime.
Member Function Documentation
GetActionTime()
float WorkTime.GetActionTime () inline
Gets the length of the shift
Returns
the length of the shift
Definition at line 36 of file WorkTime.cs.
     {
         return actionTime;
     }
References actionTime.
Referenced by Person.DecideNextActionState().
GetTimeTillWorkStart()
float WorkTime.GetTimeTillWorkStart (float currTime) inline
Returns the time remaining until the start of the shift
Parameters
currTime The current day time
Returns
Time till the shift starts
Definition at line 47 of file WorkTime.cs.
     {
         return (StartTime - currTime + 86400) % 86400;
     }
References StartTime.
Referenced by Person.DecideNextActionState(), and Person.SetDefaultParameters().
Member Data Documentation
actionTime
float WorkTime.actionTime private
Definition at line 17 of file WorkTime.cs.
Referenced by GetActionTime().
Property Documentation
StartTime
float WorkTime.StartTime get private set
When his shift starts
Definition at line 9 of file WorkTime.cs.
 { get; private set; }
Referenced by GetTimeTillWorkStart(), and WorkTime().
EndTime
float WorkTime.EndTime get private set
When his shift ends
Definition at line 14 of file WorkTime.cs.
 { get; private set; }
Referenced by WorkTime().
The documentation for this struct was generated from the following file:
Assets/Scripts/DataTypes/WorkTime.cs